spring:
  application:
    name: one-by-one
  redis:
    host: 10.211.55.6
    port: 6379
    password: 123456
    database: 0
server:
  port: 9012

# prometheus
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 通过web方式，暴露所有端点
  metrics:
    tags:
      application=${spring.application.name}: